spring:
  application:
    name: REST-API
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:h2-test
      driver-class-name: org.h2.Driver
      username: sa
      password:
      #initialization-mode: always
      #schema: classpath:/schema.sql
      #data: classpath:/data.sql
      generate-unique-name: false
      maximum-pool-size: 4
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enable: true
      path: /h2-console
